language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install tox
script:
- pytest
- tox
deploy:
  provider: pypi
  user: "finish.06"
  password:
    secure: k8+4bG/k5z65J0D1FKpjC1TV70B0hoVPk+H0157sUGQ24B66rswNM+3piRZ8/IELDxNF35O5wvOaLkyhhQTg+og5J1Nl2AsTW5TkEkumF2Dm3H35iQgvuGdLS6TtIBN6g8s+ZAjueeiHJ2K3Zal/ks3IgSHWHWdgPzUayGuCqNv5dhyQhez74OL8UmE9uql8oNV+e5JiUxUTVhTbC08IWMX2wKexg3yjEuxEjulCoHrZWBKTwGW2/Dtb8zWIYPAfE1oV+s9f5gXffnCL5Uz2DG28gDWnCKNJeIGNQFGJ+cJMFc7uKt9z2UrGlbitvyss6y0AplMTpQ0jD7Lz3haZ0Sq7PXkB5KhwuqHpgD7Q56/LzhdLgZrr/8hoDtic2rbDHvz9++HaWNa1041PjQD8zgsA3f0XS09xJySqdI3W+Y6dfWiYHOoYhOWhmI3IVHDvGmZOmg3kDxp8vb+OYf0q32lhtruOAsByxkDHbIiUeuHFtQvpzxzGVcnSC4rPletkvGmsBXAztEIDbTbVRmUWV58bFuZ4Rl4li/zaZuEO98YXogafyCGoVy6XL7XS0GtSYEPs2rfna0TblpJ3h+1jdn9yhrK2IEZLoceFc8HwzS6gFFwiv63Yg+XZZqGexycnrm3n4vOuNyjRzbzEdw2o7r8VXxtWtTx4MdyLx1DJMPw=
  true:
    branch: master
    tags: true
